
# =========================
# Codex CLI config.toml
# =========================
# Rule: In each "CHOOSE ONE" block, uncomment EXACTLY ONE line.


# -------------------------
# Model (string)
# -------------------------
# CHOOSE ONE:
model = "gpt-5"
# model = "o3"
# model = "o4-mini"

# -------------------------
# Reasoning effort (string)
# -------------------------

# CHOOSE ONE:
model_reasoning_effort = "high"
# model_reasoning_effort = "medium"
# model_reasoning_effort = "low"
# model_reasoning_effort = "minimal"


# -------------------------
# Approval policy (string)
# -------------------------
# CHOOSE ONE:
# approval_policy = "on-request"
# approval_policy = "untrusted"
# approval_policy = "on-failure"
approval_policy = "never"

# -------------------------
# Sandbox mode (string)
# -------------------------
# CHOOSE ONE:
sandbox_mode = "danger-full-access"   # no sandbox
# sandbox_mode = "workspace-write"     # writes allowed in cwd/tmp only
# sandbox_mode = "read-only"           # default in docs: no writes, no network

network_access = true

# -------------------------
# File opening and UI settings
# -------------------------
file_opener = "vscode"                    # Opens files in VS Code when clicked
show_raw_agent_reasoning = true           # Show raw reasoning content (if available)

# -------------------------
# Desktop notifications
# -------------------------
notify = ["notify-send", "Codex"]         # Desktop notifications for task completion

# -------------------------
# Shell Environment Policy
# -------------------------
[shell_environment_policy]
# Secure baseline: only essential environment variables
ignore_default_excludes = false   # Extra protection: drops vars with KEY/SECRET/TOKEN
include_only = [
    # Core essentials (always needed)
    "PATH",          # Required for finding executables
    "HOME",          # Home directory reference
    "USER",          # Username
    "SHELL",         # Shell interpreter
    
    # System locale (prevents encoding issues)
    "LANG",          # Primary locale
    "LC_*",          # All locale settings
    
    # Terminal & editor
    "TERM",          # Terminal type for proper display
    "EDITOR",        # Default editor
    "VISUAL",        # Visual editor fallback
    
    # Directories
    "PWD",           # Current working directory
    "OLDPWD",        # Previous directory
    "TMPDIR",        # Temporary directory location
    
    # Linux desktop standards
    "XDG_*",         # XDG Base Directory specs
    
    # Python development
    "PYTHON*",       # Python paths and settings
    "PIP_*",         # Pip configuration
    "VIRTUAL_ENV*",  # Virtual environment paths
    "CONDA_*",       # Conda/Anaconda settings
    "PYENV_*",       # Pyenv version management
    
    # Node.js development
    "NODE_*",        # Node.js settings
    "NPM_*",         # NPM configuration
    "NVM_*",         # Node Version Manager
    "PNPM_*",        # PNPM package manager
    "YARN_*"         # Yarn package manager
]

# NEVER add: "*_KEY", "*_SECRET", "*_TOKEN", "AWS_*", "AZURE_*", "GCP_*"

[tools]
# Enable the native Responses web_search tool (same as `--search`).
web_search = true
# (alias supported for backwards-compat):
#web_search_request = true

# -------------------------
# History persistence
# -------------------------
[history]
persistence = "save-all"          # Keeps conversation history across sessions
# max_bytes = 10485760            # Optional: limit history size

# -------------------------
# Project trust settings
# -------------------------
[projects."/home/alif/Documents/GitHub/codex"]
trust_level = "trusted"           # Skip security prompts for this repo

